# Generated by Django 5.2 on 2025-04-10 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('empleado_id', models.IntegerField(max_length=10)),
                ('usuario_alta', models.IntegerField(max_length=10)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('usuario_modif', models.IntegerField(blank=True, max_length=10, null=True)),
                ('fecha_modif', models.DateTimeField(blank=True, null=True)),
                ('usuario_baja', models.IntegerField(blank=True, max_length=10, null=True)),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
