# Generated by Django 5.2 on 2025-04-10 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authservice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='usuario_baja',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='usuario_modif',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
