version: "3.13"  # "3.13" puede dar advertencia; 3.8 es estable

services:
  web:
    container_name: django
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=wms
      - DB_USER=root
      - DB_PASSWORD=1234
      - DB_HOST=db
      - DB_PORT=3306
    depends_on:
      - db
    command: python manage.py runserver 0.0.0.0:8000

  db:
    image: mariadb:10.5
    container_name: mariadb
    restart: always
    environment:
      MARIADB_DATABASE: wms
      MARIADB_ROOT_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
