# Generated by Django 5.2 on 2025-04-10 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('codigo_barras', models.CharField(max_length=50, unique=True)),
                ('id_categoria', models.IntegerField()),
                ('id_marca', models.IntegerField()),
                ('id_proveedor', models.IntegerField()),
                ('unidad_medida', models.CharField(max_length=10)),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('stock_minimo', models.IntegerField()),
                ('stock_maximo', models.IntegerField()),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
